// AUTOGENERATED by scripts/build-catalog.ts. Do not edit by hand.
// Run `pnpm catalog` (or `pnpm start` which runs it via prestart) to regenerate.

import type { ComponentType } from 'react';

// ---------- @jv/ui ----------
import ActionSheetThemedDemo, { meta as ActionSheetThemedMeta } from '@jv/ui/src/ActionSheetThemed.demo';
import AnimatedFabDemo, { meta as AnimatedFabMeta } from '@jv/ui/src/AnimatedFab.demo';
import AnimatedViewDemo, { meta as AnimatedViewMeta } from '@jv/ui/src/AnimatedView.demo';
import AvatarDemo, { meta as AvatarMeta } from '@jv/ui/src/Avatar.demo';
import ButtonDemo, { meta as ButtonMeta } from '@jv/ui/src/Button.demo';
import CardDemo, { meta as CardMeta } from '@jv/ui/src/Card.demo';
import CardScrollerDemo, { meta as CardScrollerMeta } from '@jv/ui/src/CardScroller.demo';
import ChipDemo, { meta as ChipMeta } from '@jv/ui/src/Chip.demo';
import ConfirmationModalDemo, { meta as ConfirmationModalMeta } from '@jv/ui/src/ConfirmationModal.demo';
import ContainerDemo, { meta as ContainerMeta } from '@jv/ui/src/Container.demo';
import CustomCardDemo, { meta as CustomCardMeta } from '@jv/ui/src/CustomCard.demo';
import ErrorBoundaryDemo, { meta as ErrorBoundaryMeta } from '@jv/ui/src/ErrorBoundary.demo';
import FloatingButtonDemo, { meta as FloatingButtonMeta } from '@jv/ui/src/FloatingButton.demo';
import HeaderDemo, { meta as HeaderMeta } from '@jv/ui/src/Header.demo';
import IconDemo, { meta as IconMeta } from '@jv/ui/src/Icon.demo';
import ListLinkDemo, { meta as ListLinkMeta } from '@jv/ui/src/ListLink.demo';
import MultiStepDemo, { meta as MultiStepMeta } from '@jv/ui/src/MultiStep.demo';
import PaceRingDemo, { meta as PaceRingMeta } from '@jv/ui/src/PaceRing.demo';
import PageLoaderDemo, { meta as PageLoaderMeta } from '@jv/ui/src/PageLoader.demo';
import PlaceholderDemo, { meta as PlaceholderMeta } from '@jv/ui/src/Placeholder.demo';
import SafeWrapperDemo, { meta as SafeWrapperMeta } from '@jv/ui/src/SafeWrapper.demo';
import ScreenContentDemo, { meta as ScreenContentMeta } from '@jv/ui/src/ScreenContent.demo';
import SkeletonDemo, { meta as SkeletonMeta } from '@jv/ui/src/Skeleton.demo';
import SkeletonLoaderDemo, { meta as SkeletonLoaderMeta } from '@jv/ui/src/SkeletonLoader.demo';
import TabButtonDemo, { meta as TabButtonMeta } from '@jv/ui/src/TabButton.demo';
import ThemedTextDemo, { meta as ThemedTextMeta } from '@jv/ui/src/ThemedText.demo';
import ThemeFlatListDemo, { meta as ThemeFlatListMeta } from '@jv/ui/src/ThemeFlatList.demo';
import ThemeFooterDemo, { meta as ThemeFooterMeta } from '@jv/ui/src/ThemeFooter.demo';
import ThemeScrollerDemo, { meta as ThemeScrollerMeta } from '@jv/ui/src/ThemeScroller.demo';
import ThemeTabsDemo, { meta as ThemeTabsMeta } from '@jv/ui/src/ThemeTabs.demo';
import ThemeToggleDemo, { meta as ThemeToggleMeta } from '@jv/ui/src/ThemeToggle.demo';
import ToggleDemo, { meta as ToggleMeta } from '@jv/ui/src/Toggle.demo';

// ---------- @jv/forms ----------
import CheckboxDemo, { meta as CheckboxMeta } from '@jv/forms/src/Checkbox.demo';
import CounterDemo, { meta as CounterMeta } from '@jv/forms/src/Counter.demo';
import DatePickerDemo, { meta as DatePickerMeta } from '@jv/forms/src/DatePicker.demo';
import FormTabsDemo, { meta as FormTabsMeta } from '@jv/forms/src/FormTabs.demo';
import InputDemo, { meta as InputMeta } from '@jv/forms/src/Input.demo';
import SelectDemo, { meta as SelectMeta } from '@jv/forms/src/Select.demo';
import SelectableDemo, { meta as SelectableMeta } from '@jv/forms/src/Selectable.demo';
import SliderDemo, { meta as SliderMeta } from '@jv/forms/src/Slider.demo';
import SwitchDemo, { meta as SwitchMeta } from '@jv/forms/src/Switch.demo';
import TextInputDemo, { meta as TextInputMeta } from '@jv/forms/src/TextInput.demo';
import TimePickerDemo, { meta as TimePickerMeta } from '@jv/forms/src/TimePicker.demo';

export type DemoMeta = {
  title: string;
  description: string;
  variants: string[];
};

export type DemoEntry = {
  pkg: string;
  component: string;
  Demo: ComponentType<any>;
  meta: DemoMeta;
};

export const catalog: DemoEntry[] = [
  // @jv/ui
  { pkg: '@jv/ui', component: 'ActionSheetThemed', Demo: ActionSheetThemedDemo, meta: ActionSheetThemedMeta },
  { pkg: '@jv/ui', component: 'AnimatedFab', Demo: AnimatedFabDemo, meta: AnimatedFabMeta },
  { pkg: '@jv/ui', component: 'AnimatedView', Demo: AnimatedViewDemo, meta: AnimatedViewMeta },
  { pkg: '@jv/ui', component: 'Avatar', Demo: AvatarDemo, meta: AvatarMeta },
  { pkg: '@jv/ui', component: 'Button', Demo: ButtonDemo, meta: ButtonMeta },
  { pkg: '@jv/ui', component: 'Card', Demo: CardDemo, meta: CardMeta },
  { pkg: '@jv/ui', component: 'CardScroller', Demo: CardScrollerDemo, meta: CardScrollerMeta },
  { pkg: '@jv/ui', component: 'Chip', Demo: ChipDemo, meta: ChipMeta },
  { pkg: '@jv/ui', component: 'ConfirmationModal', Demo: ConfirmationModalDemo, meta: ConfirmationModalMeta },
  { pkg: '@jv/ui', component: 'Container', Demo: ContainerDemo, meta: ContainerMeta },
  { pkg: '@jv/ui', component: 'CustomCard', Demo: CustomCardDemo, meta: CustomCardMeta },
  { pkg: '@jv/ui', component: 'ErrorBoundary', Demo: ErrorBoundaryDemo, meta: ErrorBoundaryMeta },
  { pkg: '@jv/ui', component: 'FloatingButton', Demo: FloatingButtonDemo, meta: FloatingButtonMeta },
  { pkg: '@jv/ui', component: 'Header', Demo: HeaderDemo, meta: HeaderMeta },
  { pkg: '@jv/ui', component: 'Icon', Demo: IconDemo, meta: IconMeta },
  { pkg: '@jv/ui', component: 'ListLink', Demo: ListLinkDemo, meta: ListLinkMeta },
  { pkg: '@jv/ui', component: 'MultiStep', Demo: MultiStepDemo, meta: MultiStepMeta },
  { pkg: '@jv/ui', component: 'PaceRing', Demo: PaceRingDemo, meta: PaceRingMeta },
  { pkg: '@jv/ui', component: 'PageLoader', Demo: PageLoaderDemo, meta: PageLoaderMeta },
  { pkg: '@jv/ui', component: 'Placeholder', Demo: PlaceholderDemo, meta: PlaceholderMeta },
  { pkg: '@jv/ui', component: 'SafeWrapper', Demo: SafeWrapperDemo, meta: SafeWrapperMeta },
  { pkg: '@jv/ui', component: 'ScreenContent', Demo: ScreenContentDemo, meta: ScreenContentMeta },
  { pkg: '@jv/ui', component: 'Skeleton', Demo: SkeletonDemo, meta: SkeletonMeta },
  { pkg: '@jv/ui', component: 'SkeletonLoader', Demo: SkeletonLoaderDemo, meta: SkeletonLoaderMeta },
  { pkg: '@jv/ui', component: 'TabButton', Demo: TabButtonDemo, meta: TabButtonMeta },
  { pkg: '@jv/ui', component: 'ThemedText', Demo: ThemedTextDemo, meta: ThemedTextMeta },
  { pkg: '@jv/ui', component: 'ThemeFlatList', Demo: ThemeFlatListDemo, meta: ThemeFlatListMeta },
  { pkg: '@jv/ui', component: 'ThemeFooter', Demo: ThemeFooterDemo, meta: ThemeFooterMeta },
  { pkg: '@jv/ui', component: 'ThemeScroller', Demo: ThemeScrollerDemo, meta: ThemeScrollerMeta },
  { pkg: '@jv/ui', component: 'ThemeTabs', Demo: ThemeTabsDemo, meta: ThemeTabsMeta },
  { pkg: '@jv/ui', component: 'ThemeToggle', Demo: ThemeToggleDemo, meta: ThemeToggleMeta },
  { pkg: '@jv/ui', component: 'Toggle', Demo: ToggleDemo, meta: ToggleMeta },

  // @jv/forms
  { pkg: '@jv/forms', component: 'Checkbox', Demo: CheckboxDemo, meta: CheckboxMeta },
  { pkg: '@jv/forms', component: 'Counter', Demo: CounterDemo, meta: CounterMeta },
  { pkg: '@jv/forms', component: 'DatePicker', Demo: DatePickerDemo, meta: DatePickerMeta },
  { pkg: '@jv/forms', component: 'FormTabs', Demo: FormTabsDemo, meta: FormTabsMeta },
  { pkg: '@jv/forms', component: 'Input', Demo: InputDemo, meta: InputMeta },
  { pkg: '@jv/forms', component: 'Select', Demo: SelectDemo, meta: SelectMeta },
  { pkg: '@jv/forms', component: 'Selectable', Demo: SelectableDemo, meta: SelectableMeta },
  { pkg: '@jv/forms', component: 'Slider', Demo: SliderDemo, meta: SliderMeta },
  { pkg: '@jv/forms', component: 'Switch', Demo: SwitchDemo, meta: SwitchMeta },
  { pkg: '@jv/forms', component: 'TextInput', Demo: TextInputDemo, meta: TextInputMeta },
  { pkg: '@jv/forms', component: 'TimePicker', Demo: TimePickerDemo, meta: TimePickerMeta },
];

export function findDemo(pkg: string, component: string): DemoEntry | undefined {
  return catalog.find((d) => d.pkg === pkg && d.component === component);
}
