#!/usr/bin/env tsx
/**
 * build-catalog — globs packages/*\/src/**\/*.demo.tsx and regenerates
 * apps/showcase/catalog/data.ts with explicit imports + a flat catalog
 * array. Re-run on every package change (also runs via showcase's `prestart`).
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

const repoRoot = resolve(__dirname, '../../..');
const packagesDir = resolve(repoRoot, 'packages');
const outFile = resolve(__dirname, '../catalog/data.ts');

type Entry = { pkg: string; component: string; importPath: string };

function walk(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    const stat = statSync(full);
    if (stat.isDirectory()) walk(full, acc);
    else if (full.endsWith('.demo.tsx')) acc.push(full);
  }
  return acc;
}

function collect(): Entry[] {
  const pkgs = readdirSync(packagesDir).filter((p) => {
    const srcDir = join(packagesDir, p, 'src');
    try {
      return statSync(srcDir).isDirectory();
    } catch {
      return false;
    }
  });

  const entries: Entry[] = [];
  for (const pkg of pkgs) {
    const srcDir = join(packagesDir, pkg, 'src');
    const demos = walk(srcDir);
    for (const file of demos) {
      const name = file.split('/').pop()!.replace('.demo.tsx', '');
      const rel = relative(srcDir, file).replace('.tsx', '');
      entries.push({
        pkg: `@jv/${pkg}`,
        component: name,
        importPath: `@jv/${pkg}/src/${rel}`,
      });
    }
  }
  entries.sort((a, b) => a.pkg.localeCompare(b.pkg) || a.component.localeCompare(b.component));
  return entries;
}

function render(entries: Entry[]): string {
  const safeName = (e: Entry) => `${e.pkg.replace('@jv/', '').replace(/[^a-zA-Z0-9]/g, '')}_${e.component}`;
  const imports = entries
    .map((e) => `import ${safeName(e)}Demo, { meta as ${safeName(e)}Meta } from '${e.importPath}';`)
    .join('\n');

  const rows = entries
    .map((e) => `  { pkg: '${e.pkg}', component: '${e.component}', Demo: ${safeName(e)}Demo, meta: ${safeName(e)}Meta },`)
    .join('\n');

  return `// AUTOGENERATED by scripts/build-catalog.ts. Do not edit by hand.
// Run \`pnpm catalog\` (or \`pnpm start\` via prestart) to regenerate.

import type { ComponentType } from 'react';

${imports}

export type DemoMeta = { title: string; description: string; variants: string[] };
export type DemoEntry = { pkg: string; component: string; Demo: ComponentType<any>; meta: DemoMeta };

export const catalog: DemoEntry[] = [
${rows}
];

export function findDemo(pkg: string, component: string): DemoEntry | undefined {
  return catalog.find((d) => d.pkg === pkg && d.component === component);
}
`;
}

const entries = collect();
const source = render(entries);
writeFileSync(outFile, source);
console.log(`Wrote ${outFile} — ${entries.length} demos.`);
