#!/usr/bin/env node
// Aggregate every manifest in catalog/templates/ into:
//   catalog/index.json  — machine-readable flattened index (templates + all screens)
//   catalog/CATALOG.md  — human-browsable catalog grouped by category
//
// Usage: node scripts/catalog/build-index.mjs

import path from 'node:path';
import fs from 'node:fs';
import { loadManifests, writeJson, CATALOG_DIR, REPO_ROOT } from './lib.mjs';
import { identifiersOf } from './style.mjs';

const manifests = loadManifests();
if (!manifests.length) {
  console.error('No manifests found — run: node scripts/catalog/scan.mjs --all');
  process.exit(1);
}

const templates = [];
const screens = [];
const componentIndex = {}; // componentName -> [template names]
const identifiers = {}; // "style:glass" -> { count, templates:{name:n}, evidence:[...] }

for (const { name, manifest: m } of manifests) {
  templates.push({
    name,
    title: m.title || name,
    description: m.description,
    idea: m.idea || null,
    source: m.source,
    stack: m.stack,
    design: m.design,
    layouts: m.layouts,
    counts: m.counts,
    tags: m.tags || [],
    styleProfile: m.styleProfile || null,
    patterns: m.patterns || {},
  });
  for (const [token, evidence] of Object.entries(identifiersOf(m))) {
    const e = (identifiers[token] ||= { count: 0, templates: {}, evidence: [] });
    e.count += evidence.length;
    e.templates[name] = (e.templates[name] || 0) + evidence.length;
    e.evidence.push(...evidence.slice(0, 8));
  }
  for (const s of m.screens || []) {
    screens.push({ ...s, template: name });
  }
  for (const group of ['elements', 'forms', 'layout']) {
    for (const c of m.components?.[group] || []) {
      (componentIndex[c] ||= []).push(name);
    }
  }
}

const categories = {};
for (const s of screens) (categories[s.category] ||= []).push(s);

const index = {
  generatedBy: 'app-templates/scripts/catalog/build-index.mjs',
  counts: {
    templates: templates.length,
    screens: screens.length,
    categories: Object.keys(categories).length,
    components: Object.keys(componentIndex).length,
    identifiers: Object.keys(identifiers).length,
  },
  templates,
  screens,
  components: componentIndex,
  identifiers: Object.fromEntries(Object.entries(identifiers).sort()),
};
writeJson(path.join(CATALOG_DIR, 'index.json'), index);

// ---- human-readable catalog -------------------------------------------------
const lines = [];
lines.push('# Screen Catalog');
lines.push('');
lines.push('> Generated by `node scripts/catalog/build-index.mjs` — do not edit by hand.');
lines.push('');
lines.push(`${templates.length} templates · ${screens.length} screens · ${Object.keys(categories).length} categories`);
lines.push('');
lines.push('## Templates');
lines.push('');
lines.push('| Template | Screens | Styling | Backend | Layouts | Source |');
lines.push('|---|---|---|---|---|---|');
for (const t of templates) {
  const layoutTypes = [...new Set(t.layouts.map((l) => l.type).filter((x) => x !== 'root'))].join(', ') || 'stack';
  const src = t.source?.repo ? `[${t.source.repo}](https://github.com/${t.source.repo})` : t.source?.localPath || '';
  lines.push(`| **${t.name}** — ${t.title !== t.name ? t.title : ''} | ${t.counts?.screens ?? ''} | ${t.stack?.styling ?? ''} | ${t.stack?.backend ?? ''} | ${layoutTypes} | ${src} |`);
}
lines.push('');
lines.push('## Screens by category');
for (const cat of Object.keys(categories).sort()) {
  const list = categories[cat];
  lines.push('');
  lines.push(`### ${cat} (${list.length})`);
  lines.push('');
  lines.push('| Screen | Template | Kind | Path | Key components |');
  lines.push('|---|---|---|---|---|');
  for (const s of list.sort((a, b) => a.template.localeCompare(b.template) || a.id.localeCompare(b.id))) {
    lines.push(`| ${s.id} | ${s.template} | ${s.kind} | \`${s.path}\` | ${(s.components || []).slice(0, 5).join(', ')} |`);
  }
}
lines.push('');
fs.writeFileSync(path.join(CATALOG_DIR, 'CATALOG.md'), lines.join('\n'));

// ---- style & pattern identifier reference -----------------------------------
const sl = [];
sl.push('# Style & Pattern Identifiers');
sl.push('');
sl.push('> Generated by `node scripts/catalog/build-index.mjs` — do not edit by hand.');
sl.push('');
sl.push('Namespaced tokens for fine-grained selection in `catalog:search` (free text or');
sl.push('`--style`) and remix plan `style` blocks. Example: *"meditation and travel app,');
sl.push('`style:glass` screens, `layout:drawer+tabs`, `settings:toggles`"*.');
sl.push('');
sl.push('## Template style profiles');
sl.push('');
sl.push('| Template | Family | Dominant traits |');
sl.push('|---|---|---|');
for (const t of templates) {
  if (!t.styleProfile) continue;
  sl.push(`| **${t.name}** | ${t.styleProfile.family} | ${(t.styleProfile.dominant || []).join(', ')} |`);
}
const byNs = {};
for (const [token, e] of Object.entries(identifiers)) {
  const ns = token.split(':')[0];
  (byNs[ns] ||= []).push([token, e]);
}
for (const ns of Object.keys(byNs).sort()) {
  sl.push('');
  sl.push(`## ${ns}:`);
  sl.push('');
  sl.push('| Identifier | Found in | Examples |');
  sl.push('|---|---|---|');
  for (const [token, e] of byNs[ns].sort((a, b) => b[1].count - a[1].count)) {
    const tpls = Object.entries(e.templates).sort((a, b) => b[1] - a[1]).map(([n, c]) => `${n} (${c})`).slice(0, 6).join(', ');
    sl.push(`| \`${token}\` | ${tpls} | ${[...new Set(e.evidence)].slice(0, 3).join(', ')} |`);
  }
}
sl.push('');
fs.writeFileSync(path.join(CATALOG_DIR, 'STYLES.md'), sl.join('\n'));

console.log(`indexed ${templates.length} templates, ${screens.length} screens, ${Object.keys(categories).length} categories`);
console.log(`→ ${path.relative(REPO_ROOT, path.join(CATALOG_DIR, 'index.json'))}`);
console.log(`→ ${path.relative(REPO_ROOT, path.join(CATALOG_DIR, 'CATALOG.md'))}`);
