#!/usr/bin/env node
// Aggregate every manifest in catalog/templates/ into:
//   catalog/index.json  — machine-readable flattened index (templates + all screens)
//   catalog/CATALOG.md  — human-browsable catalog grouped by category
//
// Usage: node scripts/catalog/build-index.mjs

import path from 'node:path';
import fs from 'node:fs';
import { loadManifests, writeJson, CATALOG_DIR, REPO_ROOT } from './lib.mjs';

const manifests = loadManifests();
if (!manifests.length) {
  console.error('No manifests found — run: node scripts/catalog/scan.mjs --all');
  process.exit(1);
}

const templates = [];
const screens = [];
const componentIndex = {}; // componentName -> [template names]

for (const { name, manifest: m } of manifests) {
  templates.push({
    name,
    title: m.title || name,
    description: m.description,
    idea: m.idea || null,
    source: m.source,
    stack: m.stack,
    design: m.design,
    layouts: m.layouts,
    counts: m.counts,
    tags: m.tags || [],
  });
  for (const s of m.screens || []) {
    screens.push({ ...s, template: name });
  }
  for (const group of ['elements', 'forms', 'layout']) {
    for (const c of m.components?.[group] || []) {
      (componentIndex[c] ||= []).push(name);
    }
  }
}

const categories = {};
for (const s of screens) (categories[s.category] ||= []).push(s);

const index = {
  generatedBy: 'app-templates/scripts/catalog/build-index.mjs',
  counts: {
    templates: templates.length,
    screens: screens.length,
    categories: Object.keys(categories).length,
    components: Object.keys(componentIndex).length,
  },
  templates,
  screens,
  components: componentIndex,
};
writeJson(path.join(CATALOG_DIR, 'index.json'), index);

// ---- human-readable catalog -------------------------------------------------
const lines = [];
lines.push('# Screen Catalog');
lines.push('');
lines.push('> Generated by `node scripts/catalog/build-index.mjs` — do not edit by hand.');
lines.push('');
lines.push(`${templates.length} templates · ${screens.length} screens · ${Object.keys(categories).length} categories`);
lines.push('');
lines.push('## Templates');
lines.push('');
lines.push('| Template | Screens | Styling | Backend | Layouts | Source |');
lines.push('|---|---|---|---|---|---|');
for (const t of templates) {
  const layoutTypes = [...new Set(t.layouts.map((l) => l.type).filter((x) => x !== 'root'))].join(', ') || 'stack';
  const src = t.source?.repo ? `[${t.source.repo}](https://github.com/${t.source.repo})` : t.source?.localPath || '';
  lines.push(`| **${t.name}** — ${t.title !== t.name ? t.title : ''} | ${t.counts?.screens ?? ''} | ${t.stack?.styling ?? ''} | ${t.stack?.backend ?? ''} | ${layoutTypes} | ${src} |`);
}
lines.push('');
lines.push('## Screens by category');
for (const cat of Object.keys(categories).sort()) {
  const list = categories[cat];
  lines.push('');
  lines.push(`### ${cat} (${list.length})`);
  lines.push('');
  lines.push('| Screen | Template | Kind | Path | Key components |');
  lines.push('|---|---|---|---|---|');
  for (const s of list.sort((a, b) => a.template.localeCompare(b.template) || a.id.localeCompare(b.id))) {
    lines.push(`| ${s.id} | ${s.template} | ${s.kind} | \`${s.path}\` | ${(s.components || []).slice(0, 5).join(', ')} |`);
  }
}
lines.push('');
fs.writeFileSync(path.join(CATALOG_DIR, 'CATALOG.md'), lines.join('\n'));

console.log(`indexed ${templates.length} templates, ${screens.length} screens, ${Object.keys(categories).length} categories`);
console.log(`→ ${path.relative(REPO_ROOT, path.join(CATALOG_DIR, 'index.json'))}`);
console.log(`→ ${path.relative(REPO_ROOT, path.join(CATALOG_DIR, 'CATALOG.md'))}`);
