#!/usr/bin/env node
// Remix: describe an idea, get a plan composed from cataloged screens across
// templates, try variations, then materialize one into a target app.
//
//   suggest — turn an idea/direction into a remix plan skeleton
//     node scripts/catalog/remix.mjs suggest "dog walking marketplace with booking and chat" \
//       [--out plan.json] [--max 12]
//
//   apply — materialize a plan (pull every screen + deps) into a target app
//     node scripts/catalog/remix.mjs apply plan.json --to ../my-app \
//       [--variant bold] [--dry-run] [--force]
//
//   diff — compare two variants of a plan without building anything
//     node scripts/catalog/remix.mjs diff plan.json --variants base,bold
//
// Plan shape (see catalog/examples/):
// {
//   "name": "pawgo",
//   "idea": "dog walking marketplace…",
//   "base": { "template": "propia", "layout": "app/(tabs)/_layout.tsx" },
//   "design": { "from": "propia" },                       // whose theme files to take
//   "screens": [
//     { "template": "propia", "screen": "app/screens/checkout.tsx" },
//     { "template": "feedy", "screen": "app/screens/chat/[id].tsx", "as": "app/screens/chat/[id].tsx" }
//   ],
//   "variants": [
//     { "name": "with-social", "add": [{ "template": "feedy", "screen": "app/screens/add-post.tsx" }], "remove": [] }
//   ]
// }

import fs from 'node:fs';
import path from 'node:path';
import { readJson, writeJson, exists, fail, parseArgs, resolveTemplateRoot, CATALOG_DIR, REPO_ROOT } from './lib.mjs';
import { pullScreen, resolveScreenArg, collectDependencyClosure } from './pull.mjs';

const STOPWORDS = new Set(['a', 'an', 'the', 'and', 'or', 'with', 'for', 'app', 'of', 'to', 'in', 'that', 'my', 'like', 'then', 'style']);
// Domain synonyms so plain-English ideas hit catalog tags/categories.
const SYNONYMS = {
  booking: ['booking', 'reservation', 'checkout', 'trips', 'calendar', 'order'],
  marketplace: ['listings', 'product', 'detail', 'filters', 'favorites', 'checkout', 'review'],
  chat: ['chat', 'messaging', 'message'],
  social: ['feed', 'post', 'profile', 'follow', 'notifications'],
  fitness: ['workout', 'progress', 'meals', 'weight', 'health', 'steps'],
  food: ['meals', 'meal'],
  events: ['event', 'tickets', 'ticket', 'calendar'],
  travel: ['trips', 'trip', 'flight', 'stays', 'itinerary', 'map'],
  ride: ['map', 'tracking', 'driver', 'location'],
  delivery: ['order', 'tracking', 'map', 'checkout'],
  ai: ['ai', 'voice', 'suggestions', 'provider', 'assistant'],
  property: ['property', 'listings', 'booking', 'map'],
  payments: ['wallet', 'earnings', 'payments', 'subscription', 'checkout'],
  weather: ['hourly', 'location', 'map', 'overlays'],
  gambling: ['blackjack', 'slots', 'history', 'wallet'],
  auth: ['login', 'signup', 'welcome', 'forgot', 'password'],
  onboarding: ['onboarding', 'welcome', 'permission'],
};

function loadIndex() {
  const f = path.join(CATALOG_DIR, 'index.json');
  if (!exists(f)) fail('catalog/index.json missing — run: node scripts/catalog/build-index.mjs');
  return readJson(f);
}

function expandIdea(idea) {
  const words = idea.toLowerCase().split(/[^a-z0-9]+/).filter((w) => w && !STOPWORDS.has(w));
  const expanded = new Set(words);
  for (const w of words) for (const syn of SYNONYMS[w] || []) expanded.add(syn);
  return [...expanded];
}

function suggest(idea, { max = 12 } = {}) {
  const index = loadIndex();
  const keywords = expandIdea(idea);

  const scoreOf = (hay) => keywords.reduce((n, k) => n + (hay.includes(k) ? 1 : 0), 0);

  // Score templates (title/description/tags/screen tags) to pick a base
  const templateScores = index.templates
    .map((t) => {
      const screenTags = index.screens.filter((s) => s.template === t.name).flatMap((s) => s.tags || []);
      const hay = [t.name, t.title, t.description, t.idea, ...(t.tags || []), ...screenTags].join(' ').toLowerCase();
      return { name: t.name, score: scoreOf(hay), template: t };
    })
    .sort((a, b) => b.score - a.score);
  const base = templateScores[0];

  // Score screens; always keep an auth + onboarding baseline from the base template
  const scored = index.screens
    .map((s) => {
      const hay = [s.id, s.category, s.path, ...(s.tags || [])].join(' ').toLowerCase();
      let score = scoreOf(hay);
      if (s.template === base.name && score > 0) score += 0.5; // prefer staying coherent with the base
      return { ...s, _score: score };
    })
    .filter((s) => s._score > 0)
    .sort((a, b) => b._score - a._score);

  // De-dupe: one screen per (category + basename), best score wins
  const seen = new Set();
  const picks = [];
  for (const s of scored) {
    const key = s.category + ':' + path.basename(s.path);
    if (seen.has(key)) continue;
    seen.add(key);
    picks.push(s);
    if (picks.length >= max) break;
  }

  const baseLayouts = base.template.layouts.filter((l) => l.type !== 'root');
  const plan = {
    $comment: 'Remix plan generated by remix.mjs suggest — edit freely, then: remix.mjs apply <plan> --to <target>',
    name: idea.split(/\s+/).slice(0, 3).join('-').toLowerCase().replace(/[^a-z0-9-]/g, ''),
    idea,
    base: { template: base.name, layout: baseLayouts[0]?.path || null },
    design: { from: base.name },
    screens: picks.map((s) => ({ template: s.template, screen: s.path, category: s.category })),
    variants: [
      { name: 'lean', remove: picks.slice(Math.ceil(max / 2)).map((s) => ({ template: s.template, screen: s.path })), add: [], notes: 'Smaller MVP cut' },
    ],
    alternatives: templateScores.slice(1, 4).filter((t) => t.score > 0).map((t) => t.name),
  };
  return { plan, templateScores: templateScores.slice(0, 5) };
}

function resolveVariant(plan, variantName) {
  let screens = [...plan.screens];
  if (variantName && variantName !== 'base') {
    const v = (plan.variants || []).find((x) => x.name === variantName);
    if (!v) fail(`variant "${variantName}" not in plan (have: base, ${(plan.variants || []).map((x) => x.name).join(', ')})`);
    const removeKeys = new Set((v.remove || []).map((r) => r.template + '|' + r.screen));
    screens = screens.filter((s) => !removeKeys.has(s.template + '|' + s.screen));
    screens.push(...(v.add || []));
  }
  return screens;
}

function applyPlan(planFile, args) {
  const plan = readJson(path.resolve(planFile));
  const targetRoot = args.to && path.resolve(args.to);
  if (!targetRoot) fail('--to <target app root> is required');
  const dryRun = !!args['dry-run'];
  const variant = args.variant || 'base';
  const screens = resolveVariant(plan, variant);

  if (!exists(targetRoot)) {
    if (dryRun) console.log(`[dry-run] target ${targetRoot} does not exist yet — would be created`);
    else fs.mkdirSync(targetRoot, { recursive: true });
  }

  const report = [];
  const allMissing = new Set();
  const provenance = [];

  // 1. Design + layout from the base template
  const baseRoot = plan.base?.template && resolveTemplateRoot(plan.base.template);
  if (plan.base?.template && !baseRoot) fail(`base template "${plan.base.template}" not checked out (see catalog/registry.json)`);
  if (baseRoot && plan.base.layout) {
    const r = pullScreen({ sourceRoot: baseRoot, targetRoot, screenRel: plan.base.layout, dryRun, force: !!args.force, log: () => {} });
    r.missingPackages.forEach((p) => allMissing.add(p));
    provenance.push({ what: 'layout', from: plan.base.template, path: plan.base.layout, files: r.copies.length });
  }
  const designFrom = plan.design?.from && resolveTemplateRoot(plan.design.from);
  if (designFrom) {
    const manifest = readJson(path.join(CATALOG_DIR, 'templates', `${plan.design.from}.json`));
    for (const tf of manifest.design?.themeFiles || []) {
      const src = path.join(designFrom, tf);
      const dest = path.join(targetRoot, tf);
      if (exists(src) && (!exists(dest) || args.force)) {
        if (!dryRun) {
          fs.mkdirSync(path.dirname(dest), { recursive: true });
          fs.copyFileSync(src, dest);
        }
        provenance.push({ what: 'design', from: plan.design.from, path: tf });
      }
    }
  }

  // 2. Screens (cross-template)
  for (const entry of screens) {
    const srcRoot = resolveTemplateRoot(entry.template);
    if (!srcRoot) {
      report.push(`SKIPPED ${entry.template}:${entry.screen} — template not checked out`);
      continue;
    }
    const screenRel = resolveScreenArg(srcRoot, entry.template, entry.screen);
    if (!screenRel) {
      report.push(`SKIPPED ${entry.template}:${entry.screen} — screen not found`);
      continue;
    }
    const r = pullScreen({ sourceRoot: srcRoot, targetRoot, screenRel, asRel: entry.as || null, dryRun, force: !!args.force, log: () => {} });
    r.missingPackages.forEach((p) => allMissing.add(p));
    const copied = r.copies.filter((c) => c.action !== 'skip (exists)').length;
    const skipped = r.copies.length - copied;
    provenance.push({ what: 'screen', from: entry.template, path: entry.as || screenRel, files: copied, reused: skipped });
    report.push(`${dryRun ? 'would pull' : 'pulled'} ${entry.template}:${screenRel}${entry.as ? ` as ${entry.as}` : ''} (${copied} files, ${skipped} already present)`);
  }

  // 3. REMIX.md provenance report in the target
  const md = [
    `# Remix: ${plan.name || path.basename(String(planFile))}`,
    '',
    plan.idea ? `> ${plan.idea}` : '',
    '',
    `Variant: **${variant}** · Base: **${plan.base?.template ?? '—'}** · Design from: **${plan.design?.from ?? '—'}**`,
    '',
    '| Layer | Source template | Path | Files |',
    '|---|---|---|---|',
    ...provenance.map((p) => `| ${p.what} | ${p.from} | \`${p.path}\` | ${p.files ?? ''}${p.reused ? ` (+${p.reused} reused)` : ''} |`),
    '',
    allMissing.size ? `## Packages to install\n\n\`\`\`\nnpm install ${[...allMissing].sort().join(' ')}\n\`\`\`` : '',
    '',
    '## Next steps',
    '',
    '- Wire pulled screens into the layout (`app/(tabs)/_layout.tsx` tab triggers / stack routes).',
    '- Screens pulled from different templates keep their own component copies on first conflict-free write; existing files are never overwritten without `--force`, so shared names resolve to whichever template landed first — review `components/` for duplicates.',
    '- Re-run with `--variant <name>` in a fresh target dir to compare variations side by side before committing to one.',
    '',
  ].filter((l) => l !== null).join('\n');

  if (!dryRun) fs.writeFileSync(path.join(targetRoot, 'REMIX.md'), md);

  console.log(report.join('\n'));
  if (allMissing.size) console.log(`\npackages needed: ${[...allMissing].sort().join(', ')}`);
  console.log(dryRun ? '\n[dry-run] nothing written' : `\nwrote ${path.join(targetRoot, 'REMIX.md')}`);
}

function diffPlan(planFile, args) {
  const plan = readJson(path.resolve(planFile));
  const names = (args.variants || 'base').split(',').map((s) => s.trim());
  const sets = names.map((n) => ({ n, screens: new Set(resolveVariant(plan, n).map((s) => s.template + ':' + (s.as || s.screen))) }));
  const all = [...new Set(sets.flatMap((s) => [...s.screens]))].sort();
  const pad = (s, n) => String(s).padEnd(n).slice(0, n);
  console.log(pad('SCREEN', 60) + sets.map((s) => pad(s.n, 12)).join(''));
  for (const scr of all) {
    console.log(pad(scr, 60) + sets.map((s) => pad(s.screens.has(scr) ? '✓' : '—', 12)).join(''));
  }
}

const args = parseArgs(process.argv.slice(3), ['dry-run', 'force']);
const cmd = process.argv[2];
if (cmd === 'suggest') {
  const idea = args._.join(' ');
  if (!idea) fail('usage: remix.mjs suggest "<idea text>" [--out plan.json] [--max 12]');
  const { plan, templateScores } = suggest(idea, { max: args.max ? parseInt(args.max, 10) : 12 });
  console.error('template match scores: ' + templateScores.map((t) => `${t.name}=${t.score}`).join('  '));
  if (args.out) {
    writeJson(path.resolve(args.out), plan);
    console.log(`plan → ${args.out} (${plan.screens.length} screens, base: ${plan.base.template})`);
    console.log(`next: node scripts/catalog/remix.mjs apply ${args.out} --to <target> --dry-run`);
  } else {
    console.log(JSON.stringify(plan, null, 2));
  }
} else if (cmd === 'apply') {
  const planFile = args._[0];
  if (!planFile) fail('usage: remix.mjs apply <plan.json> --to <target> [--variant name] [--dry-run] [--force]');
  applyPlan(planFile, args);
} else if (cmd === 'diff') {
  const planFile = args._[0];
  if (!planFile) fail('usage: remix.mjs diff <plan.json> --variants base,lean');
  diffPlan(planFile, args);
} else {
  fail('usage: remix.mjs <suggest|apply|diff> …  (see header comment)');
}
